name: Typechecker
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
env:
  # Disable creating virtual envs instead CI/CD due to being unnecessary.
  POETRY_VIRTUALENVS_CREATE: "false"

jobs:
  test:
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
        os:
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} @ ${{ matrix.python-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install Dependencies
        # We cannot use --require-hashes here as we are using different Python versions.
        run: |
          python -m pip install "poetry==$(cat .github/requirements/.poetry_version)"
          python -m poetry install

      - name: Run Mypy
        run: mypy .
